export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const GET_USER_TRANSACTIONS_FAIL = "GET_USER_TRANSACTIONS_FAIL";
export const GET_USER_TRANSACTIONS_SUCCESS = "GET_USER_TRANSACTIONS_SUCCESS";

export const GET_ADMIN_TRANSACTIONS = "GET_ADMIN_TRANSACTIONS";
export const GET_ADMIN_TRANSACTIONS_FAIL = "GET_ADMIN_TRANSACTIONS_FAIL";
export const GET_ADMIN_TRANSACTIONS_SUCCESS = "GET_ADMIN_TRANSACTIONS_SUCCESS";
