/* ADMIN */
export const GET_PRICING = "GET_PRICING";
export const GET_PRICING_SUCCESS = "GET_PRICING_SUCCESS";
export const GET_PRICING_FAIL = "GET_PRICING_FAIL";

export const UPDATE_PRICING = "UPDATE_PRICING";
export const UPDATE_PRICING_SUCCESS = "UPDATE_PRICING_SUCCESS";
export const UPDATE_PRICING_FAIL = "UPDATE_PRICING_FAIL";
