export const EDIT_PROFILE_EMAIL = "EDIT_PROFILE_EMAIL";
export const PROFILE_SUCCESS_EMAIL = "PROFILE_SUCCESS_EMAIL";
export const PROFILE_ERROR_EMAIL = "PROFILE_ERROR_EMAIL";

export const EDIT_PROFILE_PASSWORD = "EDIT_PROFILE_PASSWORD";
export const PROFILE_SUCCESS_PASSWORD = "PROFILE_SUCCESS_PASSWORD";
export const PROFILE_ERROR_PASSWORD = "PROFILE_ERROR_PASSWORD";

export const EDIT_PROFILE_VERIFY_PHONE = "EDIT_PROFILE_VERIFY_PHONE";
export const PROFILE_SUCCESS_VERIFY_PHONE = "PROFILE_SUCCESS_VERIFY_PHONE";
export const PROFILE_ERROR_VERIFY_PHONE = "PROFILE_ERROR_VERIFY_PHONE";
