/* ADMIN */
export const GET_COUPONES = "GET_COUPONES";
export const GET_COUPONES_SUCCESS = "GET_COUPONES_SUCCESS";
export const GET_COUPONES_FAIL = "GET_COUPONES_FAIL";

export const ADD_NEW_COUPONE = "ADD_NEW_COUPONE";
export const ADD_NEW_COUPONE_SUCCESS = "ADD_NEW_COUPONE_SUCCESS";
export const ADD_NEW_COUPONE_FAIL = "ADD_NEW_COUPONE_FAIL";

export const DELETE_COUPONE = "DELETE_COUPONE";
export const DELETE_COUPONE_SUCCESS = "DELETE_COUPONE_SUCCESS";
export const DELETE_COUPONE_FAIL = "DELETE_COUPONE_FAIL";

/* USERS */
export const USER_GET_COUPONES = "USER_GET_COUPONES";
export const USER_GET_COUPONES_SUCCESS = "USER_GET_COUPONES_SUCCESS";
export const USER_GET_COUPONES_FAIL = "USER_GET_COUPONES_FAIL";

export const USER_VALIDATE_COUPONES = "USER_VALIDATE_COUPONES";
export const USER_VALIDATE_COUPONES_SUCCESS = "USER_VALIDATE_COUPONES_SUCCESS";
export const USER_VALIDATE_COUPONES_FAIL = "USER_VALIDATE_COUPONES_FAIL";
