/* USERS */

export const GET_MEMBERSHIP = "GET_MEMBERSHIP";
export const GET_MEMBERSHIP_SUCCESS = "GET_MEMBERSHIP_SUCCESS";
export const GET_MEMBERSHIP_FAIL = "GET_MEMBERSHIP_FAIL";

export const USER_MEMBERSHIP_SUBSCRIPTION = "USER_MEMBERSHIP_SUBSCRIPTION";
export const USER_MEMBERSHIP_SUBSCRIPTION_SUCCESS =
  "USER_MEMBERSHIP_SUBSCRIPTION_SUCCESS";
export const USER_MEMBERSHIP_SUBSCRIPTION_FAIL =
  "USER_MEMBERSHIP_SUBSCRIPTION_FAIL";
